### ISSUE TITLE
Check git repo

### ISSUE THREAD

**Issue by elimoss** [bhattlab/kraken2_classification#13]
Workflow should check its own git repo for newer commits on remote origin and halt if it is out of date.

**Comment by bsiranosian** [comment]
Have you done this before? What's the strategy?

**Comment by elimoss** [comment]
Haven't done it before. I'm basing its feasibility on a very quick google search. I'm thinking something involving pygit, the phrase `os.path.realpath(__file__)`, some glue and a hammer.
