### ISSUE TITLE
Kraken2 memory requirements for large dbs

### ISSUE THREAD

**Issue by tamburinif** [bhattlab/kraken2_classification#17]
Do something more intelligent for memory requirements for large genbank databases, or put into config. Right now hardcoded for feb 2019 db but many will likely start using /oak/stanford/scg/lab_asbhatt/data/program_indices/kraken2/kraken_custom_jan2020/genbank_genome_chromosome_scaffold

**Comment by bsiranosian** [comment]
I think the scheme of what's in there already is fine, it gives extra memory and time for the genbank database, and a standard for everything else. We can add to the list of extra mem required databases as needed. Could do something like scaling based on DB size but I don't think it's worth it.

**Comment by tamburinif** [comment]
Sure, doesn’t have to be fancy as long as someone remembers to update the hard coded path list when there’s a new db
