### ISSUE TITLE
update dependency in yaml file

### ISSUE THREAD

**Issue by ammaraziz** [bhattlab/kraken2_classification#22]
Hi there,

Create snakemake pipeline, it's fantastic and exactly what I was after. Thank you for making it public so others can use it. 

I noticed the dependencies listed in the `yaml` file are incomplete, especially for some R packages:
```
  - r-rafalib
  - bioconductor-cmapR
  - r-compositions
  - r-zcompositions
  - bioconductor-ALDEx2
  - bracken
```

Regards,

Ammar

**Comment by bsiranosian** [comment]
Hi, thank you for the kind words! 

We tend to use this pipeline with singularity images for all software (so users don't have to install anything). You can find the commands to run with singularity on the usage page. That yaml file hasn't been updated in two years it looks like!

Still, if you find the conda environment useful, I can add these things and test it.

**Comment by bsiranosian** [comment]
Closed in favor of containerized steps
