### ISSUE TITLE
.krak_bracken.report missing or changed name?

### ISSUE THREAD

**Issue by ammaraziz** [bhattlab/kraken2_classification#23]
Hi there,

I noticed the snakemake file specifies `.krak_bracken.report`, however on the current version of `kraken2 2.1.2` the file seems to be named `.krak_bracken_species.report`. I'm not positive about the change in name (maybe  `.krak_bracken.report` is missing from my outputs) but looking at `downstream_processing` for example, the associated R script and output mentions species. 

Therefore I think in the snakefile `.krak_bracken.report` -> `.krak_bracken_species.report`

Regards,

Ammar

**Comment by bsiranosian** [comment]
Hi, thanks for catching this. I'll look at the new Kraken version and see how the outputs have changed.

**Comment by bsiranosian** [comment]
Finally updated to the latest containers and fixed this error.
