### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by s4251484** [bhattlab/kraken2_classification#25]
Hi thanks for developing this pipeline, it is very useful! Just wonder how can I cite this pipeline?

**Comment by bsiranosian** [comment]
Thanks, and great question. It seems like github now has citation support, I'll add something in a minute.

**Comment by s4251484** [comment]
That will be great! thanks!

**Comment by bsiranosian** [comment]
The citation file has been added and this repo now has a DOI. You can see the suggested citation on the right side of github under "cite this repository" 

If you have a preprint where you used the software, I'd love to read it. 

Cheers, 
Ben
