### ISSUE TITLE
Merging fails with one sample

### ISSUE THREAD

**Issue by elimoss** [bhattlab/kraken2_classification#8]
When running the pipeline on one sample, the post-processing script fails with the following error:

>Loading data from 1 kraken/bracken results.
>Processing at taxonomic levels: Domain, Phylum, Class, Order, Family, Genus, Species
>Error in merge_kraken_df_list(report.list) : Must be a list longer than 1
>Calls: many_files_to_matrix_list -> merge_kraken_df_list
>Execution halted

**Comment by elimoss** [comment]
I was able to spoof this by inputing my single sample twice under an alias, but a single sample input still breaks stuff

**Comment by bsiranosian** [comment]
Fixed https://github.com/bhattlab/kraken2_classification/commit/42865c78bcf4b1888a5fbf95834f0044b6c88a03
